query TeacherRatingsPageQuery($id: ID!) {
  node(id: $id) {
    ... on Teacher {
      ...TeacherInfo_teacher
    }
  }
}

fragment TeacherInfo_teacher on Teacher {
  lastName
  numRatings
  avgRating
  ...TeacherTags_teacher
  ...TeacherFeedback_teacher
}

fragment TeacherTags_teacher on Teacher {
  teacherRatingTags {
    tagCount
    tagName
  }
}
fragment TeacherFeedback_teacher on Teacher {
  numRatings
  avgDifficulty
  wouldTakeAgainPercent
}
